import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="border-4 border-pink-500 min-h-dvh flex flex-col">
          <header className="border">
            <Image src="/logo-2.webp" alt="logo" width={90} height={113} />
          </header>
          <main className="border flex-grow">{children}</main>
          <footer className="border">Footer</footer>
        </div>
      </body>
    </html>
  );
}
